### ISSUE TITLE
What is the redirect URL?

### ISSUE THREAD

**Issue by SAngelCuadrosV** [alexandrtovmach/react-microsoft-login#1]
I wanna know what's the redirect URL that I have to set on my Microsoft App.

TY.

**Comment by alexandrtovmach** [comment]
Hello,
You need to use URL's of your hosting or your development server. For example here my list:
```
http://localhost:5100 // it's for testing on my local machine
https://alexandrtovmach.github.io/react-microsoft-login // it's for production demo page
```
