### ISSUE TITLE
Need Help In correct Implementaion

### ISSUE THREAD

**Issue by jmandivarapu1** [alexandrtovmach/react-microsoft-login#10]
Hi,

I really like the simple way you implemented it.

I am facing one issue.

1. I have kept my MS login button in http://localhost:3000/#/login

2. When User clicks the button. It opens the mslogin in New tab.

3. Once I login it redirects me to to http://localhost:3000/#/login in the new tab only. but with no data being printed.

4. I saw your example Implemeted the same. Can't figure out where I made the mistake. I want to come to same page with data.

If needed open to share my code
```
 <MicrosoftLogin 
 withUserData={withUserData}
 clientId={""} 
 authCallback={this.loginHandler} 
graphScopes={["user.read"]}/>
```

**Comment by alexandrtovmach** [comment]
Hello,

@jmandivarapu1 Could you share your code please?

**Comment by jmandivarapu1** [comment]
Sorry for late reply.

But here my code 
```
  constructor(props) {
    super(props);
    this.state = {
      withUserData: true,   
    }
  }

render() {
    const { email, password,withUserData} = this.state;
    return (
<div>
 <MicrosoftLogin 
 withUserData={withUserData}
 clientId={""} 
 authCallback={this.loginHandler} 
graphScopes={["user.read"]}/>
</div>

```
<img width="1210" alt="Screen Shot 2019-04-03 at 10 47 55 PM" src="https://user-images.githubusercontent.com/21245519/55526478-43c13f80-5663-11e9-9d94-1d6ccf9c3a0c.png">

**Comment by jmandivarapu1** [comment]
FOR SIMPLICITY and for easy reproducing the issues I moved my button to separate page for sample.
You can Use above code and this too

```
import React, {Component} from 'react';
import {Badge, Col, Nav, NavItem, NavLink, Row, TabContent, TabPane} from 'reactstrap';
import classnames from 'classnames';
import MicrosoftLogin from "react-microsoft-login";

class StudentClassView extends Component {

  constructor(props) {
    super(props);
    this.toggle = this.toggle.bind(this);
    this.state = {
      withUserData: true,
    };
  }

  render() {
    const { withUserData} = this.state;

    return (
      <div className="animated fadeIn">

        <MicrosoftLogin
          withUserData={withUserData}
          clientId={"7366a2a5-f456-493a-8e53-ccb7b310fa2d"}
          authCallback={this.loginHandler}
          graphScopes={["user.read"]} />
       
      </div>
    );
  }
}

export default StudentClassView;

```

<img width="813" alt="Screen Shot 2019-04-03 at 10 58 31 PM" src="https://user-images.githubusercontent.com/21245519/55526945-0cec2900-5665-11e9-83d3-98653f5bbb9a.png">

**Comment by alexandrtovmach** [comment]
Thanks,

I've tested with provided code and seems like it works for me. Only one thing can be the problem:

Your link contains the "#", probably you try use route without it

**Comment by jmandivarapu1** [comment]
Awesome. you are correct # is a problem I removed it using BrowserRouter from react-dom and changed the redirect URL to http://localhost:3000/login and it worked like a charm.

Thank You for all your help.
