### ISSUE TITLE
Children property issue in typescript

### ISSUE THREAD

**Issue by vigneshRajenthiran** [alexandrtovmach/react-microsoft-login#102]
**Steps to reproduce:**

1. Installed the latest version of react-microsoft-login
2. Rendered and tried to add children in the MicrosoftLogin component
3. Got typescript error " property 'children' does not exist on type 'intrinsicattributes & microsoftloginprops'"

**Attachments:**

	                                                                          <MicrosoftLogin
											clientId={office_clientId}
											graphScopes={graphScopes}
											prompt={'select_account'}
											useLocalStorageCache={true}
											authCallback={authHandler}
											buttonTheme={'dark'}
											children={
												 <Tooltip title={'One Drive'}>
													 <IconButton
													 	onClick={(e:any) => {
													 		folderClicked = true;
													 	}}
													 	color='inherit'
													 >
														<Office style={{ height: '20px', width: '20px' }} />
													</IconButton>
												 </Tooltip>
											}
										/>

**Comment by hylink-oscar-caballero** [comment]
No updates at December 16, 2022.

**Comment by alexandrtovmach** [comment]
I'm planning to start working on next version of this package to use new msal, this issue will be fixed in it

No timeframes I can share

**Comment by eduardomuchak** [comment]
yourPath/node_modules/react-microsoft-login/dist/MicrosoftLogin.d.ts:

`import React from "react";
import { AuthResponse, AuthError, UserAgentApplication } from "msal";
import { User } from "@microsoft/microsoft-graph-types";
import { MicrosoftLoginButtonTheme } from "./MicrosoftLoginButton";
declare type MicrosoftLoginPrompt = "login" | "select_account" | "consent" | "none";
interface MicrosoftLoginProps {
    /**
     * Application (client) ID
     */
    clientId: string;
    /**
     * Callback function which takes two arguments (error, authData)
     */
    authCallback: (error: AuthError | null, result?: AuthResponse | (AuthResponse & User), instance?: UserAgentApplication) => void;
    /**
     * Array of Graph API permission names.
     */
    graphScopes?: string[];
    /**
     * A URL indicating a directory that MSAL can request tokens from.
     * In Azure AD, it is of the form https://<instance>/<tenant>>, where <instance> is the directory host
     * (e.g. https://login.microsoftonline.com) and <tenant> is an identifier within the directory itself
     * (e.g. a domain associated to the tenant, such as contoso.onmicrosoft.com,
     * or the GUID representing the TenantID property of the directory)
     * In Azure AD B2C, it is of the form https://<instance>/tfp/<tenantId>/<policyName>/
     */
    tenantUrl?: string;
    /**
     * You can configure the URI to which it should redirect after sign-out by setting postLogoutRedirectUri.
     * This URI should also be registered as the logout URI in your application registration.
     */
    postLogoutRedirectUri?: string;
    /**
     * Name of theme for button style.
     */
    buttonTheme?: MicrosoftLoginButtonTheme;
    /**
     * Make an additional request to GraphAPI to get user data.
     */
    withUserData?: boolean;
    /**
     * Enable detailed logs of authorization process.
     */
    debug?: boolean;
    /**
     * Additional class name string.
     */
    className?: string;
    /**
     * Prompt behavior for interactive requests
     * https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior
     */
    prompt?: MicrosoftLoginPrompt;
    /**
     * Force redirect login strategy. This strategy used by default on IE browsers to avoid issues.
     * If set true login will be executed only with redirect strategy in all browsers.
     */
    forceRedirectStrategy?: boolean;
    /**
     * The redirect URI of the application, this should be same as the value in the application registration portal.
     */
    redirectUri?: string;
    /**
     * Set whether to use localStorage or sessionStorage for MSAL Single Sign-On
     * https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso
     */
    useLocalStorageCache?: boolean;

    **children?: React.ReactNode;**
}
declare const MicrosoftLogin: React.FunctionComponent<MicrosoftLoginProps>;
export default MicrosoftLogin;
`

**Comment by alexandrtovmach** [comment]
Fixed in v2.0.1

https://github.com/alexandrtovmach/react-microsoft-login/commit/851e81ea533b5cf95b733514c6f25c0c683a6f9a
