### ISSUE TITLE
[Question] How to create the login button for next js typescript

### ISSUE THREAD

**Issue by dtcMLOps** [alexandrtovmach/react-microsoft-login#108]
Hi @alexandrtovmach,

thanks for this wonderful tool.

I am learning about frontend development and I have started with a project where I need a simple login button with a pop-up window. I was wondering if I create a component as you mentioned in the example code it will give me the login button? or that is something apart that I will need to develop?

I want to achieved this button in my frontend login page

![Screenshot from 2023-01-27 08-05-18](https://user-images.githubusercontent.com/115469901/215093863-13ef941d-9d46-4501-8e5c-91975855e6a9.png)

**Comment by alexandrtovmach** [comment]
It's a button that delivered by this package by default
