### ISSUE TITLE
Reply URL

### ISSUE THREAD

**Issue by itdeciphered** [alexandrtovmach/react-microsoft-login#12]
Where do you set or define the reply url ? It has to match the reply url configured for the application

**Comment by itdeciphered** [comment]
For reference this is a requirement for organizations that do not allow office365 applications to be configured as a multi-tenant application.
Useafe of the /common endpoint is not supported for such applications created after '10/15/2018'

**Comment by alexandrtovmach** [comment]
@itdeciphered Thanks for a question, I'll take a look

**Comment by alexandrtovmach** [comment]
Added `redirectUri` property in [1.6.0](https://www.npmjs.com/package/react-microsoft-login/v/1.6.0)
