### ISSUE TITLE
Prop for avoiding pop-up

### ISSUE THREAD

**Issue by Ueland** [alexandrtovmach/react-microsoft-login#14]
This module works great, but i have a (hopefully) minor feature request. And that is to have the ability (as a prop) to avoid using a pop-up to start the sign in process. (Given how browsers dislike pop-ups)

**Comment by alexandrtovmach** [comment]
@Ueland Could you explain more about expected result? As I understood you want to make auto-login, but as I know it's impossible in case with Microsoft Authorization Process.

**Comment by Ueland** [comment]
I want that when I click the login button, the login process continues in the current window. Instead of as now, where it opens a new window. So no, not auto-login :)

**Comment by alexandrtovmach** [comment]
Okay, I see. Microsoft provide us with two options to authenticate:
- popup
- redirect

In case of bad popup support in IE and Edge browsers, they recommend to use popup as default strategy and redirect for MS browsers. And in this package I'm using the [same approach](https://github.com/alexandrtovmach/react-microsoft-login/blob/master/src/MicrosoftLogin.tsx#L98).

If you think that is useful to have a prop to set strategy ― let me know.

**Comment by Ueland** [comment]
Yes, a prop for strategy would be great to have.

**Comment by alexandrtovmach** [comment]
Okay, I'll take a look in a week

**Comment by alexandrtovmach** [comment]
@Ueland Added `forceRedirectStrategy` prop in v1.4.0

Example of usage:
```
<MicrosoftLogin
    forceRedirectStrategy
    clientId={YOUR_CLIENT_ID}
    authCallback={authHandler}
/>
```

**Comment by Ueland** [comment]
Thanks! Will give it a test
