### ISSUE TITLE
change response_type to "code"

### ISSUE THREAD

**Issue by bamerf** [alexandrtovmach/react-microsoft-login#40]
Need code rather than access_token, possible to do this?

**Comment by alexandrtovmach** [comment]
I'm not sure about that. What is the case?

**Comment by bamerf** [comment]
I'm getting my users to log in through the front-end only one time to give us AppFolder access, if I get the `code` back instead of the `access_token` I can use that code in our backend to request a refresh token with which I'll be making requests for access tokens without them having to log in again. 

This is the link for the flow I'm talking about: [https://docs.microsoft.com/en-us/graph/auth-v2-user](url)

Your package requests `access_token` by default for the `response_type`.

I was wondering if there was a way to change that.

**Comment by alexandrtovmach** [comment]
@bamerf Flow that you described it's antipattern. You should implement the full auth through your server

**Comment by divsbhalala** [comment]
@alexandrtovmach you mean response_type=code is not supported here and we can not do it using this lib?
we have to use different lib if we want code as a response

**Comment by alexandrtovmach** [comment]
@divsbhalala This lib provides client side auth, which *SHOULD NOT* work with `refreshToken`, because it's not secure. Please read about difference between "authorization" and "authentication".
