### ISSUE TITLE
Cachelocation is not supported

### ISSUE THREAD

**Issue by ravihani** [alexandrtovmach/react-microsoft-login#41]
Please see attached screenshot. Could you please let me know how do i configure cachelocation, it seems by default sessionstorage is not supported on my virtual device.

![ms error](https://user-images.githubusercontent.com/4699823/74065091-14d1d380-49c2-11ea-9636-74c1b2dca4fe.png)

**Comment by alexandrtovmach** [comment]
@ravihani Thank you for report.
Seems like you trying to use this package in React Native, but it's not supported
