### ISSUE TITLE
Is there a way to get the profile picture from the data returned?

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [alexandrtovmach/react-microsoft-login#42]
Hi there,

Great work with this package. Please is there a way to get the user's profile picture? It seems to be accessible with the User.Read permission.

Thanks.

**Comment by alexandrtovmach** [comment]
@muyiwaoyeniyi Yes, `User.Read` are allowing you to get profile picture, but I'm not sure that's should be done by this package. Just make an additional request in your code by using token that you get from `react-microsoft-login`

**Comment by muyiwaoyeniyi** [comment]
Ok thanks. And thanks for this package.
Taiwo

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 6, 2020 at 11:23 AM, Alexandr Tovmach<notifications@github.com> wrote:   
Closed #42.
