### ISSUE TITLE
Getting CORS error

### ISSUE THREAD

**Issue by reachtokish** [alexandrtovmach/react-microsoft-login#47]
I'm getting the below CORS error while trying to implement this library

![image](https://user-images.githubusercontent.com/10685261/84648734-0f156d00-af23-11ea-88e8-e208ebdec5a8.png)

Below is my component
```jsx
<MicrosoftLogin
  clientId={CLIENT_ID}
  authCallback={authHandler}
  debug={true}
  tenantUrl="https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/authorize"
/>
```

Can anyone kindly tell me what could be the possible reason for this error?

**Comment by alexandrtovmach** [comment]
Thanks for report 👍 
Seems like you're using tenantUrl, so probably you haven't allowed localhost in your organization

**Comment by reachtokish** [comment]
Thanks @alexandrtovmach for the info. I will check my azure configuration.

**Comment by reachtokish** [comment]
This issue is resolved. So my azure application is not multi-tenant and that is why I can't use /common in the url. And in that case I have to pass an extra parameter which is ```tenantUrl```. And tenantUrl also I was passing wrong. Below is the example code which worked for me if that helps anyone.

```jsx
<MicrosoftLogin
  clientId="YOUR_CLIENT_ID"
  authCallback={(error, authData) => authHandler(error, authData)}
  tenantUrl="https://login.microsoftonline.com/YOUR_TENANT_ID"
/>
```

Thanks for the great library!

**Comment by alexandrtovmach** [comment]
@reachtokish Thank you :+1:
