### ISSUE TITLE
Module not found: Can't resolve 'msal'

### ISSUE THREAD

**Issue by dorsegal** [alexandrtovmach/react-microsoft-login#5]
install via `npm i --save react-microsoft-login`

./node_modules/react-microsoft-login/dist/MicrosoftLogin.js
Module not found: Can't resolve 'msal' in node_modules\react-microsoft-login\dist'

**Comment by dorsegal** [comment]
After adding it to devDependecies manually the issue is resolved

**Comment by alexandrtovmach** [comment]
Thank you for report, I'll check it out.

**Comment by alexandrtovmach** [comment]
@dorsegal fixed in version **1.1.2**
```
yarn add react-microsoft-login@latest
```

let me know if you still have any problems
