### ISSUE TITLE
Callback not called on Microsoft Edge

### ISSUE THREAD

**Issue by francisjavier** [alexandrtovmach/react-microsoft-login#51]
Problem:
Callback is not called in Microsoft Edge 44.18362.449.0, it is called in Chrome and Firefox

Not sure if related to Known issues documented by Microsoft:

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-known-issues-ie-edge-browsers#issues-due-to-security-zones

Here is a small video of the issue, the redirect comes back but doesn't hit the callback so the user stays on the same page. On Chrome and Firefox since the callback is called it shows the next page of the UI.

![Microsoft Login](https://user-images.githubusercontent.com/6133264/87758270-64b29300-c7c9-11ea-9bbc-eb84334438a0.gif)

**Comment by alexandrtovmach** [comment]
Thank you for reporting! I'm busy with other things at the moment, would you like to contribute? I'll take a look aproximately in September

**Comment by alexandrtovmach** [comment]
@francisjavier Could you provide logs? Also, could you try to reproduce this issue with example:
https://alexandrtovmach.github.io/react-microsoft-login/
