### ISSUE TITLE
I want Signout in Microsoft button need.

### ISSUE THREAD

**Issue by nakawankuma** [alexandrtovmach/react-microsoft-login#52]
**Is your feature request related to a problem? Please describe.**
I think so User need request sign out button. 
I don't touch msal object internal.

**Describe the solution you'd like**
<MicrosoftLogin clientId= {msalConfig.auth.clientId} authCallback={authHandler} mode="SignOut" />
or
<MicrosoftLogOut clientId= {msalConfig.auth.clientId} authCallback={authHandler}/>

**Describe alternatives you've considered**
I made onSignOut method is 
    const onSignOut=()=> {
        const myMSALObj = new Msal.UserAgentApplication(msalConfig);
        myMSALObj.logout();
        window.location.reload();
    }

But Sign in use MicrosoftLogin, sign out use Msal. 
This is so ugly.

**Comment by alexandrtovmach** [comment]
@nakawankuma Sounds interesting, but I'm not sure that's providing additional button is okay. Instead, we can provide method (from your example) directly from `react-microsoft-login` like:
```
import { logout } from "react-microsoft-login";
...
logout();
```

Currently, I'm busy with other things, would you like to implement it and contribute? I can investigate in September or later. Thank you!

**Comment by alexandrtovmach** [comment]
From version 1.12.0 and older you can get msal instance as third argument in callback function, after success auth. With this instance you can do many things and logout is one of them:

```
import React, { useState } from "react";
import MicrosoftLogin from "../../dist";

const ExaplePage = () => {
  const [msalInstance, onMsalInstanceChange] = useState();

  const loginHandler = (err, data, msal) => {
    console.log(err, data);
    // some actions
    if (!err && data) {
      onMsalInstanceChange(msal);
    }
  };

  const logoutHandler = () => {
    msalInstance.logout();
  };

  return msalInstance ? (
    <button onClick={logoutHandler}>Logout</button>
  ) : (
    <MicrosoftLogin
      clientId={clientId}
      authCallback={loginHandler}
    />
  )
};

export default ExaplePage;
```
