### ISSUE TITLE
Popup is blocked on login

### ISSUE THREAD

**Issue by mueezahmad** [alexandrtovmach/react-microsoft-login#55]
<img width="1318" alt="Screen Shot 2020-08-09 at 2 45 03 PM" src="https://user-images.githubusercontent.com/60815431/89729416-f91db780-da4e-11ea-92b2-fb1a4d942947.png">
<img width="1156" alt="Screen Shot 2020-08-09 at 2 45 51 PM" src="https://user-images.githubusercontent.com/60815431/89729427-105ca500-da4f-11ea-8031-f32a1891ca89.png">

Hi Mate,

It's a super plugin thanks for that. I am facing some weird issue, it was fine few days back.
When i try to login the app i got pop-up block error.

Also i have noticed at that time the authHandler function return "authResponseWithAccessToken" undefined in the result, but when i refresh the page, i am logged in successfully.

Also attached the screen shot, one with the console, other showing that i am logged in in microsoft account
Can you please help me in that.

Thanks

**Comment by mueezahmad** [comment]
<img width="1315" alt="Screen Shot 2020-08-09 at 3 31 06 PM" src="https://user-images.githubusercontent.com/60815431/89730167-bca18a00-da55-11ea-9853-fd3f024c18cf.png">
for reference..!

**Comment by jadir-junior** [comment]
you can fix thats error?

**Comment by alexandrtovmach** [comment]
Hello,
Thank you for reporting issue, I'll take a look on a next week

**Comment by alexandrtovmach** [comment]
Should be fixed in version [1.10.2+](https://www.npmjs.com/package/react-microsoft-login/v/1.10.2)?

**Comment by shahmaulik** [comment]
Facing same issue with version (1.15.0)
