### ISSUE TITLE
Any way to actually use the token that is retrieved?

### ISSUE THREAD

**Issue by Admin-NWIF** [alexandrtovmach/react-microsoft-login#57]
I'd like to use the token I get from authenticating the user to see what groups they are apart of. Seems like you can request user data/user.read scope for Microsoft Graph but I don't see how I might actually reference that data with this lib?

**Comment by alexandrtovmach** [comment]
Please refer to official [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/use-the-api) for this info, because I'm not confident with that. For sure, you need to request some list of scopes, that required for specific API requests, and use `accessToken` as bearer auth header
