### ISSUE TITLE
Cannot read property 'accessToken' of undefined

### ISSUE THREAD

**Issue by DharmendraNaberly** [alexandrtovmach/react-microsoft-login#58]
TypeError: Cannot read property 'accessToken' of undefined
    at MicrosoftLogin.getUserData (VM1264 MicrosoftLogin.js:294)
    at eval (VM1264 MicrosoftLogin.js:233)
Getting this issue in version @1.8.5

**Comment by alexandrtovmach** [comment]
@DharmendraNaberly Thank you for the report! I'd suggest using the latest version

**Comment by vinceplayer** [comment]
any news?

**Comment by alexandrtovmach** [comment]
Closed in favor of #63
