### ISSUE TITLE
login popup doesn't closed 

### ISSUE THREAD

**Issue by dorsegal** [alexandrtovmach/react-microsoft-login#6]
The Microsoft login page pops up but after completing the log in the login popup redirect back to the home page instead of closing and running authCallback function

This is how I use it.
export class FileSettingsModalComp extends React.PureComponent<FileSettingsModalProps> {

  openWithOffice = (err, response) => {
    // this.handleClickOutside()
    console.log(err, response)
  };

  render() {
    return (
      <div>
            <MicrosoftLogin
              clientId={config.microsoft.APP_ID}
              authCallback={this.openWithOffice}
              graphScopes={["Files.ReadWrite.All"]}
              withUserData={true}
            />
          </div>
    );
  }
}

**Comment by dorsegal** [comment]
since I am using it as a none root element I had to do `new UserAgentApplication(APP_ID, null, () => { })` seperatly

**Comment by mateomurphy** [comment]
Hi @dorsegal  I'm having the same problem, how did you get this to work?

**Comment by dorsegal** [comment]
@mateomurphy added `new UserAgentApplication(APP_ID, null, () => { })` on my parent component

https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/498
