### ISSUE TITLE
navigator is not defined at new TelemetryManager

### ISSUE THREAD

**Issue by DharmendraNaberly** [alexandrtovmach/react-microsoft-login#60]
On refreshing page getting this error
ReferenceError: navigator is not defined at new TelemetryManager

**Comment by alexandrtovmach** [comment]
@DharmendraNaberly Thanks for reporting! Could you provide more details? It's seems weird, because this package shouldn't anything like this

**Comment by DharmendraNaberly** [comment]
![ms_error (1)](https://user-images.githubusercontent.com/53552327/92487973-d04e2680-f1a2-11ea-845a-9f920284f1d8.png)

**Comment by alexandrtovmach** [comment]
Do you use SSR?

**Comment by alexandrtovmach** [comment]
I'm pretty sure this issue is not related to the package directly. It looks like you trying to use `react-microsoft-login` in SSR or mobile development, but it's not expected.

Feel free to reopen this issue with more details
