### ISSUE TITLE
Unable to get response or data in authHandler

### ISSUE THREAD

**Issue by AbdulAhad125** [alexandrtovmach/react-microsoft-login#61]

**Comment by AbdulAhad125** [comment]
Hey i am using this react-microsoft-login for simple microsoft authentication. I had created and registered application and follows all steps and i successfully redirect to redirect uri now i am facing an issue that i am not getting any data in auth handler all i getting is undeifned when i console data. Here is my code

```
`import React, { FC } from 'react';
import MicrosoftLogin from "react-microsoft-login";

const Login: FC<any> = () => {

  const authHandler = (err: any, data: any) => {
    console.log(data);
  };
  return (
    <div>
       <MicrosoftLogin 
        clientId={'2605a4bf-3a94-4e4f-ab05-7d620c85c248'} 
        redirectUri={'http://localhost:3000/login'}
        graphScopes={["user.read"]}
        authCallback={authHandler}
        withUserData={true}
        />
    </div>
  )
}

export default Login;`
```
Please can anyone help me out in what is problem in here and suggest the correct way of implementing the auth flow.
Thanks in advance.

**Comment by AbdulAhad125** [comment]
@alexandrtovmach Can you please have a look.

**Comment by AbdulAhad125** [comment]
@alexandrtovmach  1 thing more to mention when i console error i get this

**Comment by alexandrtovmach** [comment]
@AbdulAhad125 Could you check with latest version

**Comment by alexandrtovmach** [comment]
@AbdulAhad125 Feel free to reopen if issue still exist
