### ISSUE TITLE
Cannot read property 'accessToken' of undefined

### ISSUE THREAD

**Issue by yogeshchauhan** [alexandrtovmach/react-microsoft-login#63]
**Steps to reproduce:**

**Actual result:**
Cannot read property 'accessToken' of undefined

**Expected behaviour:**
After login, I want the Microsoft user data. In the second time, I am able to get the data as the cookie has been generated successfully on my browser.

**Attachments:**
![Screenshot 2020-09-21 at 3 17 20 PM](https://user-images.githubusercontent.com/6008210/93753583-00bfa700-fc1e-11ea-920a-7191defdc662.png)

![Screenshot 2020-09-21 at 3 18 07 PM](https://user-images.githubusercontent.com/6008210/93753600-04532e00-fc1e-11ea-81e7-7f5ee47b8d57.png)

**Additional context:**
The Auth is secured by OTP settings. I am using 1.10.1 version of the library.

**Comment by vinceplayer** [comment]
any news?

**Comment by alexandrtovmach** [comment]
I can't reproduce the issue. Tested on:
- Chrome 87 (Ubuntu)
- Firefox 79 (Ubuntu)

But I think I found where is the issue. Could you try a new version [1.10.2](https://www.npmjs.com/package/react-microsoft-login/v/1.10.2)?
