### ISSUE TITLE
We should be able to change the button text

### ISSUE THREAD

**Issue by ncesar** [alexandrtovmach/react-microsoft-login#64]
I'm from Brazil and I need to change the text to PT-BR. I know that I can create a custom button but it would be way easier if I could edit just the string.

**Comment by alexandrtovmach** [comment]
Microsoft doesn't provide us with recommendation for localization, so I'm not sure that we have a plan to support any languages except English:
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-add-branding-in-azure-ad-apps
