### ISSUE TITLE
Can't get refresh token

### ISSUE THREAD

**Issue by dorsegal** [alexandrtovmach/react-microsoft-login#7]
I added permission to my app `offline_access` and added it to my scope but can't seem to get back a refresh token.

**Comment by alexandrtovmach** [comment]
`refresh_token` is cannot be obtained using browser authorization by security reasons.

**Comment by DharmendraNaberly** [comment]
Is there any way i can get it,  as gmail api is providing.

**Comment by alexandrtovmach** [comment]
@DharmendraNaberly No it's not possible because that's anti pattern.
To work with refresh token you need to implement server side auth process. For example with http://www.passportjs.org/
