### ISSUE TITLE
Page getting refreshed twice

### ISSUE THREAD

**Issue by reachtokish** [alexandrtovmach/react-microsoft-login#70]
```javascript
<MicrosoftLogin
  clientId={CLIENT_ID}
  authCallback={(error, authData, msalInstance) => authHandler(error, authData, msalInstance)}
  tenantUrl={`https://login.microsoftonline.com/${TENANT_ID}`}
  forceRedirectStrategy={true}
/>
```
Above is the component I'm using for MS SSO implementation. As it is visible that I'm using `forceRedirectStrategy` and it is actually working, and I'm getting the idToken in url. But when sucessfully login happens and it redirects to my react app, the react app gets refreshed again and replace the url with error response.

Am I missing anything which I need to pass to the component additionally?

**Comment by alexandrtovmach** [comment]
Can you try to reproduce it with example?
alexandrtovmach.github.io/react-microsoft-login

**Comment by reachtokish** [comment]
Closing the issue as I have resolved it some other way. Thanks, and it's a great library btw!!
