### ISSUE TITLE
Fails to install - Husky command  not found

### ISSUE THREAD

**Issue by chrisb911** [alexandrtovmach/react-microsoft-login#81]
Had a problem with this with our app since a couple of days so have tried to install on a clean react app and getting same problem.  My Environment is Mac OSX 11.3, npx 6.14.8 npm, 6.14.8 node 14.15.1

1. npx create-react-app testapp
2. npm i React-microsoft-login

gives me the following:

> react-microsoft-login@1.13.3 postinstall /Users/chrisbartlett/Development/tmp/node_modules/react-microsoft-login
> is-ci || husky install

sh: is-ci: command not found
sh: husky: command not found
npm WARN enoent ENOENT: no such file or directory, open '/Users/chrisbartlett/Development/tmp/package.json'
npm WARN react-microsoft-login@1.13.3 requires a peer of react@17.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-microsoft-login@1.13.3 requires a peer of react-dom@17.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! react-microsoft-login@1.13.3 postinstall: `is-ci || husky install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-microsoft-login@1.13.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by alexandrtovmach** [comment]
Oops :laughing: 
Could you downgrade to 1.12.1 for now. I'll fix it tomorrow

**Comment by chrisb911** [comment]
Sure thing.

Chris







Chris Bartlett

Email: ***@***.***
Phone:  +44 (0) 1672 563 110

Mobile: +44 (0) 7780 730 782

Web: www.dahu.co.uk


This e-mail and attachments are the
property of Dahu Ltd. It is intended only for
the person or entity to which it is
addressed and may contain information
that is privileged, confidential, or otherwise
protected from disclosure. Distribution or
copying of this e-mail, or the information
contained herein, to anyone other than the
intended recipient is prohibited. If you have
received this e-mail in error, please
immediately notify the sender by e-mail
and telephone and please delete and
destroy any copies of this e-mail.

**Comment by alexandrtovmach** [comment]
Related issue:
https://github.com/nenadfilipovic/iot-manager/issues/13

**Comment by alexandrtovmach** [comment]
Released fix in v1.13.4, so feel free to upgrade
