### ISSUE TITLE
authCallback not call when set forceRedirectStrategy=true

### ISSUE THREAD

**Issue by Mrliupengye** [alexandrtovmach/react-microsoft-login#82]
```jsx
  <MicrosoftLogin
          clientId={LOGIN_MICROSOFT_CLIENTID}
          authCallback={handleAzureCallBack}
          redirectUri={REDIRECT_URI}
          prompt="login"
          forceRedirectStrategy={true}
          debug={true}
          children={
           // custom Login button
          }
   />
```
```jsx
  const handleAzureCallBack = (error, data) => {
    if (error !== null) return;
    const params = {
      access_token: data?.accessToken || data?.authResponseWithAccessToken?.accessToken,
      issuer: 'azure',
    };
    // ......
  };
```
If i don't use parameters forceRedirectStrategy, the authCallback function will be called well, but when i set forceRedirectStrategy=true, authCallback not call.

**Comment by Mrliupengye** [comment]
![image](https://user-images.githubusercontent.com/13655888/120205145-33657900-c25c-11eb-91c4-9872f3075c2f.png)

**Comment by alexandrtovmach** [comment]
Thanks for report, which version do you use?

**Comment by Mrliupengye** [comment]
> Thanks for report, which version do you use?

hello, my version is:
"react-microsoft-login": "^1.12.1"

**Comment by alexandrtovmach** [comment]
okay, so first suggestion will be ― try to use latest one

**Comment by alexandrtovmach** [comment]
also, could you try to reproduce it with demo page?
https://alexandrtovmach.github.io/react-microsoft-login/

**Comment by alexandrtovmach** [comment]
@Mrliupengye could you?
