### ISSUE TITLE
ClientAuthError: Error: could not resolve endpoints. Please check network and try again.

### ISSUE THREAD

**Issue by KirianCaumes** [alexandrtovmach/react-microsoft-login#83]
Hi,
I'm totally stuck with this error :
![image](https://user-images.githubusercontent.com/24525092/122395642-7a9b7b80-cf77-11eb-8a3d-fcbd04adad4b.png)

I think my code looks like exactly yours in your demo:

```jsx
<MicrosoftLogin
    clientId="f13f9d18-cb41-470b-bab4-4f287c4e07d5"
    redirectUri="https//localhost:3000"
    authCallback={(err, data) => console.log(err, data)}
    className="aze"
    debug
    withUserData
    buttonTheme="dark"
    graphScopes={['user.read']}
/>
```

But the curious thing, is that with this clientId, it's working totaly fine on your demo:
![image](https://user-images.githubusercontent.com/24525092/122395910-c3ebcb00-cf77-11eb-9ff0-00b66c5f8721.png)

I have tried diffrent things:
- Chrome/Firefox
- Changing my internet connection (even without internet)

But none of this is changing a thing :/

Do you have an idea?

Thank you very much! 🙏

ps: I'm using the last version "1.15.0"

ps1: I've tried both "Accounts in this organizational directory only (Your company only - Single tenant)" and "Accounts in any organizational directory (Any Azure AD directory - Multitenant)"

**Comment by KirianCaumes** [comment]
Well, I guess it was those day where you are stupid and don't understand a thing.
So problem was with Pretender that was not firing an error.
So adding this in pretender fixed my problem:

```js
    this.get('https://login.microsoftonline.com/*', this.passthrough)
    this.post('https://login.microsoftonline.com/*', this.passthrough)
    this.get('https://graph.microsoft.com/*', this.passthrough)
```

Sorry for this!

**Comment by alexandrtovmach** [comment]
I like when issues resolving :+1:
