### ISSUE TITLE
Authentication code flow

### ISSUE THREAD

**Issue by filipkowal** [alexandrtovmach/react-microsoft-login#86]
I need to authenticate the user with [authentication code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) so the back-end accepts the `authorization code` instead of `authentication token`. Can it be achieved with this library? I've found out that providing `responseType="code"` to the MS API would change the response to the `authorization code`.

**Comment by axme100** [comment]
@filipkowal I'm trying to do the same thing. Are you saying that you did something like this with this library?

`<MicrosoftLogin
responseType="code"`
`</MicrosoftLogin>`

**Comment by filipkowal** [comment]
@axme100 This library doesn't support it. 

The official MS library `msal-browser` does support the `authorization code flow` but in a different way. The frontend never gets the `authorization code` directly.
After reading [these docs on the authorization code flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code) I've tried to simply create a `GET request` from the client that would include `response_type=code` but even though I've correctly configured the app in Azure AD I keep on getting `CORS` errors. It seems that getting the `autorization code` directly to frontend is not possible. 

[This discussion](https://github.com/AzureAD/microsoft-authentication-library-for-js/discussions/3822) with a `msal-browser` maintainer tackles exactly the flow we would like to achieve but the solution seems very complicated.

**Comment by cnadeau** [comment]
If it helps someone: I ended up creating the authorize URL manually and open a popup to start the flow using `response_type=code` and `response_mode=query` and I was finally able to get the flow as react-google-login does out of the box.
