### ISSUE TITLE
Can't send Tenant prop

### ISSUE THREAD

**Issue by SogenHommeTeh** [alexandrtovmach/react-microsoft-login#9]
Hi,

I was just wondering about how hard would it be for you to add the Tenant property into the button ? so that the authority called by msal would not be :
https://login.microsoftonline.com/common
but might be
https://login.microsoftonline.com/<tenant || "common">
In fact it's usefull when you wanna bring restriction about the email domain of people that can use your app.

Could you add it ?

Best regards & good job

**Comment by alexandrtovmach** [comment]
@SogenHommeTeh 
Thanks for the idea, I'll take a look.

**Comment by alexandrtovmach** [comment]
Hello, 

Added `tenantUrl` property in *v1.2.0* usage example:
```
<MicrosoftLogin
        clientId={YOUR_CLIENT_ID}
        tenantUrl={YOUR_TENANT_URL}
        authCallback={authHandler}
/>
```

How to build the URL read here:
https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/MSAL-basics
