### ISSUE TITLE
when I going to add in button clientId={YOUR_CLIENT_ID} so getting this error 

### ISSUE THREAD

**Issue by brijpatel6080** [alexandrtovmach/react-microsoft-login#91]
![image_2021_12_27T11_39_45_844Z](https://user-images.githubusercontent.com/31682945/147469832-e7dff3b8-8598-40b2-86be-c3741a376504.png)
**Steps to reproduce:**

**Actual result:**

**Expected behavior:**

**Attachments:**

**Additional context:**
help me out

**Comment by faisalur-rehman** [comment]
I am facing the same issue on ios version 14.5. Any update on this?

**Comment by alexandrtovmach** [comment]
this package is not support react-native
